name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências Web
        run: |
          cd web
          npm install

      - name: Instalar dependências API
        run: |
          cd api
          npm install

      - name: Rodar testes Jest
        run: |
          cd tests/jest
          npx jest

      - name: Build containers
        run: docker compose build
